powermock/powermock

core/src/main/java/org/powermock/core/transformers/impl/TestClassTransformer.java
core/src/test/java/org/powermock/core/transformers/impl/MainMockTransformerTest.java
core/src/test/java/org/powermock/core/transformers/impl/TestClassTransformerTest.java
core/src/test/java/powermock/test/support/MainMockTransformerTestSupport.java
modules/module-test/mockito/junit4-delegate/src/test/java/powermock/modules/test/mockito/junit4/delegate/EnclosedTest.java
modules/module-test/mockito/junit4-delegate/src/test/java/powermock/modules/test/mockito/junit4/delegate/SubclassDelegateTest.java
modules/module-test/mockito/junit4-delegate/src/test/java/powermock/modules/test/mockito/junit4/delegate/SuperClass.java

The problem can occur when @PowerMockRunnerDelegate is used and the test-class extends another class from the PowerMock classloader.
The root-cause is that the delegate-runner can be confused by the defer-constructor, which is added to the test-class by the PowerMock classloader. This pull-requests deals with the problem by making sure that test-class defer-constructors are protected (i.e. not public).

Fix "Test class can only have one constructor"-problem

---

api/mockito/src/main/java/org/powermock/api/mockito/internal/invocation/MockitoMethodInvocationControl.java
api/mockito/src/main/java/org/powermock/api/mockito/internal/mockcreation/MockCreator.java
api/mockito/src/main/java/org/powermock/api/mockito/internal/mockcreation/PowerMockMethodInterceptorFilter.java
api/mockito/src/main/java/org/powermock/api/mockito/internal/mockmaker/PowerMockMaker.java
api/mockito/src/main/java/org/powermock/api/mockito/repackaged/AcrossJVMSerializationFeature.java
api/mockito/src/main/java/org/powermock/api/mockito/repackaged/CGLIBHacker.java
api/mockito/src/main/java/org/powermock/api/mockito/repackaged/CglibMockMaker.java
api/mockito/src/main/java/org/powermock/api/mockito/repackaged/ClassImposterizer.java
api/mockito/src/main/java/org/powermock/api/mockito/repackaged/DelegatingMockitoMethodProxy.java
api/mockito/src/main/java/org/powermock/api/mockito/repackaged/MethodInterceptorFilter.java
api/mockito/src/main/java/org/powermock/api/mockito/repackaged/Mockito-LICENSE.txt
api/mockito/src/main/java/org/powermock/api/mockito/repackaged/MockitoNamingPolicy.java
api/mockito/src/main/java/org/powermock/api/mockito/repackaged/SerializableMockitoMethodProxy.java
api/mockito/src/main/java/org/powermock/api/mockito/repackaged/SerializableNoOp.java
api/mockito/src/main/java/org/powermock/api/mockito/repackaged/package-info.java
core/pom.xml
pom.xml

Fixes issue [524](https://code.google.com/p/powermock/issues/detail?id=524)
As Mockito changed the structure of this internals : renaming, package changes, visibility change, interface change. PowerMock doesn't have anymore the opportunity to hack his way by extension. 
So he best way currently is to repackage some of the mockito internals (the CGLIB related part), and change visibility where relevant. However it means that PowerMock won't use current Mockito `MockMaker`. As Mockito is progressively moving away from CGLIB, there will for sure be another implementation. Let's forget bug fixes on this front too.
A better solution has to be engineered. PR are welcome on https://github.com/mockito/mockito/

Fixes issue 524 : Mockito 1.10.9+ incompatibility, by repackaging CGLIB MockMaker

---

core/pom.xml
core/src/main/java/org/powermock/core/transformers/impl/Primitives.java
core/src/main/java/org/powermock/core/transformers/impl/TestClassTransformer.java
core/src/test/java/org/powermock/core/transformers/impl/TestClassTransformerTest.java
core/src/test/java/org/powermock/core/transformers/impl/TestPrimitives.java
core/src/test/java/powermock/test/support/MainMockTransformerTestSupport.java
modules/module-test/mockito/junit4-delegate/src/test/java/powermock/modules/test/mockito/junit4/delegate/EnclosedTest.java
modules/module-test/mockito/junit4-delegate/src/test/java/powermock/modules/test/mockito/junit4/delegate/MultipleConstructorsTest.java

Fix "Test class can only have one constructor" issue that occurs when a JUnit or 3rd-party delegate runner (specified by a PowerMockRunnerDelegate annotation) can only deal with one public constructor.
The problem occured because the method MainMockTransformer#setAllConstructorsToPublic(javassist.CtClass) makes all constructors public. This is useful for the classes that are prepared for test - but for the actual test-class it can result in multiple public constructors that confuse the delegate runner, which fails with the message "Test class can only have one constructor".
This pull-request works around the problem by having the new method TestClassTransformer#restoreOriginalConstructorsAccesses(javassist.CtClass) reverse the "constructor-publication" on test-classes and their nested …

Fix another "Test class can only have one constructor" issue

---

api/mockito/src/main/java/org/powermock/api/mockito/internal/verification/DefaultConstructorArgumentsVerfication.java

NPE occurs at the line below when `withArguments()` is passed just two arguments, where the first one is not null and the second one is null.
https://github.com/jayway/powermock/compare/master...occho:master#diff-cc5b1cb3f25544c6d7ad4d0ba720bf87R40
A simple test with a variable arity method.
https://gist.github.com/occho/32583fc23183e2aca6fa

Fix NPE constructor withArguments()

---

core/pom.xml

This version fixes an issue with java 8 default methods.

Update javassist to 3.20.0-GA

---

core/src/main/java/org/powermock/tests/utils/MockPolicyInitializer.java
core/src/main/java/org/powermock/tests/utils/impl/MockPolicyInitializerImpl.java
modules/module-impl/junit4-rule/src/main/java/org/powermock/modules/junit4/rule/PowerMockClassloaderExecutor.java
modules/module-impl/junit4-rule/src/main/java/org/powermock/modules/junit4/rule/PowerMockRule.java
modules/module-test/mockito/junit4-rule-objenesis/src/test/java/org/powermock/example/Foo.java
modules/module-test/mockito/junit4-rule-objenesis/src/test/java/org/powermock/modules/test/junit4/rule/objenesis/PowerMockRuleTest.java
modules/module-test/mockito/junit4-rule-xstream/src/test/java/org/powermock/example/Foo.java
modules/module-test/mockito/junit4-rule-xstream/src/test/java/org/powermock/modules/test/junit4/rule/xstream/PowerMockRuleTest.java

This allows creating mocks in the applyInterceptionPolicy method of MockPolicy, which in turn allows using MockPolicy together with PowerMockRule.
Fixes #581

Added refreshPolicies() to MockPolicyInitializer.

---

core/src/main/java/org/powermock/core/classloader/MockClassLoader.java
core/src/main/java/org/powermock/tests/utils/impl/AbstractTestSuiteChunkerImpl.java
modules/module-impl/agent/src/main/java/org/powermock/objectweb/asm/ClassReader.java
modules/module-impl/agent/src/main/java/org/powermock/objectweb/asm/MethodWriter.java
modules/module-impl/agent/src/main/java/sun/tools/attach/HotSpotVirtualMachine.java
modules/module-impl/junit4/src/main/java/org/powermock/modules/junit4/internal/impl/NotificationBuilder.java
modules/module-impl/junit4/src/main/java/org/powermock/modules/junit4/internal/impl/PowerMockJUnit44RunnerDelegateImpl.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1699 - “Constructors should only call non-overridable methods”. You can find more information about the issue here: https://dev.eclipse.org/sonar/rules/show/squid:S1699
Please let me know if you have any questions.
Christian

Code Quality Improvement - Constructors should only call non-overridable methods

---

api/mockito/pom.xml
examples/byte-buddy-mockito/pom.xml
pom.xml
release/with-junit-mockito-dependencies/pom.xml
release/with-testng-mockito-dependencies/pom.xml

* mockito-all is uberjar which bundles all transitive
deps into single jar (hamcrest-core and objenesis). This is bad,
becuase it disrupts Maven based dependency management. Projects
using powermock may require different version of
hamcrest-core than the one bundled in mockito-all. That will
result in hamcrest-core classes being twice on classpath
without any guarantee which one will be loaded first. That
leads to very hard to debug issues.
* added hamcrest-core as well as it is direct dependency

Replace usage of uberjar mockito-all with mockito-core

---

modules/module-impl/junit4/src/main/java/org/powermock/modules/junit4/internal/impl/PowerMockJUnit47RunnerDelegateImpl.java
modules/module-impl/junit4/src/main/java/org/powermock/modules/junit4/internal/impl/PowerMockJUnit49RunnerDelegateImpl.java

This is how rules are used by JUnit itself. It avoids different behaviour of tests when they are run with the PowerMockRunner instead of JUnit's default runner. Fixes #427.

Nest statements generated by rules.

---

reflect/src/main/java/org/powermock/reflect/internal/CandidateConstructorSearcher.java
reflect/src/main/java/org/powermock/reflect/internal/WhiteboxImpl.java
reflect/src/main/java/org/powermock/reflect/internal/comparator/ComparatorFactory.java
reflect/src/test/java/org/powermock/reflect/WhiteBoxTest.java
reflect/src/test/java/org/powermock/reflect/testclasses/ClassWithInterfaceConstructors.java
reflect/src/test/java/org/powermock/reflect/testclasses/ClassWithObjectConstructors.java
reflect/src/test/java/org/powermock/reflect/testclasses/ClassWithOverloadedConstructors.java
reflect/src/test/java/org/powermock/reflect/testclasses/ClassWithPrimitiveConstructors.java

It was the issue not with overload constructors, but with constructors with object parameters. Also supper class for arguments has not been checked, for example in this case: 
```
public class ClassWithObjectConstructors {
private final Object name;
protected ClassWithObjectConstructors(Object name) {
this.name = name;
}
public Object getName() {
return name;
}
}
```
this code threw exception 
String name = "objectConstructor";
ClassWithObjectConstructors instance = Whitebox.invokeConstructor(ClassWithObjectConstructors.class,
name);
Fix #214

Whitebox.invokeConstructor may not work as expected with overloaded constructors

---

api/mockito/src/main/java/org/powermock/api/extension/listener/AnnotationEnabler.java
modules/module-impl/testng-agent/pom.xml
modules/module-impl/testng-agent/src/main/java/org/powermock/modules/testng/PowerMockObjectFactory.java
modules/module-impl/testng/src/main/java/org/powermock/modules/testng/internal/Assumes.java
modules/module-test/mockito/testng/pom.xml
modules/module-test/mockito/testng/src/test/java/samples/powermockito/testng/staticmocking/Mockito1MockStaticTest.java
modules/module-test/mockito/testng/src/test/java/samples/powermockito/testng/staticmocking/Mockito2MockStaticTest.java
modules/module-test/mockito/testng/suite.xml
tests/utils/src/main/java/samples/powermockito/MockitoVersion.java

Implemented workaround for Mockito 1, because Mockito fix will be applied only for Mockito 2. 
https://github.com/mockito/mockito/issues/368

Fix #634 java.lang.NoClassDefFoundError: Could not initialize class org.mockito.internal.util.MockUtil

---

changelog.txt
core/src/main/java/org/powermock/core/classloader/MockClassLoader.java
modules/module-test/pom.xml
modules/module-test/testng/pom.xml
modules/module-test/testng/src/test/java/org/powermock/api/extension/proxyframework/ProxyFrameworkImpl.java
modules/module-test/testng/src/test/java/samples/testng/SimpleBaseTest.java
modules/module-test/testng/src/test/java/samples/testng/powermock647/PowerMock647.java
modules/module-test/testng/src/test/java/samples/testng/powermock647/SkipExceptionTest.java
modules/module-test/testng/src/test/java/samples/testng/powermock647/SomeClass.java
modules/module-test/testng/suite.xml

Add "org.testng.*" package to list of packaged which should always be deferred.

TestNG SkipException doesn't work with PowerMock #647

---

changelog.txt
modules/module-test/mockito/junit4/src/test/java/samples/powermockito/junit4/staticmocking/MockStaticTest.java
modules/pom.xml
reflect/src/main/java/org/powermock/reflect/internal/ParameterTypesMatcher.java
reflect/src/main/java/org/powermock/reflect/internal/WhiteboxImpl.java
tests/utils/src/main/java/samples/singleton/StaticService.java

Fix #652 PowerMock stubbing void method don't work for overloaded methods

Fix #652 PowerMock stubbing void method don't work for overloaded methods

---

changelog.txt
core/pom.xml
core/src/main/java/org/powermock/core/transformers/MockTransformer.java
core/src/main/java/org/powermock/core/transformers/impl/AbstractMainMockTransformer.java
core/src/main/java/org/powermock/core/transformers/impl/ClassMockTransformer.java
core/src/main/java/org/powermock/core/transformers/impl/InterfaceMockTransformer.java
core/src/main/java/org/powermock/core/transformers/impl/TestClassTransformer.java
core/src/main/java/org/powermock/tests/utils/impl/AbstractTestSuiteChunkerImpl.java
core/src/test/java/org/powermock/core/classloader/MockClassLoaderTest.java
core/src/test/java/org/powermock/core/transformers/impl/ClassMockTransformerTest.java
core/src/test/java/org/powermock/core/transformers/impl/TestClassTransformerTest.java
core/src/test/java/powermock/test/support/MainMockTransformerTestSupport.java
modules/module-impl/agent/src/main/java/org/powermock/modules/agent/PowerMockClassTransformer.java
modules/module-impl/junit4-rule/src/main/java/org/powermock/modules/junit4/rule/PowerMockClassloaderExecutor.java
modules/module-impl/testng/src/main/java/org/powermock/modules/testng/internal/ClassLoaderFactory.java
modules/module-test/mockito/junit4-java8/pom.xml
modules/module-test/mockito/junit4-java8/src/main/java/samples/powermockito/junit4/bugs/github510/ClassUsesInterface.java
modules/module-test/mockito/junit4-java8/src/main/java/samples/powermockito/junit4/bugs/github510/FizzBuzz.java
modules/module-test/mockito/junit4-java8/src/main/java/samples/powermockito/junit4/bugs/github510/InterfaceWithStatic.java
modules/module-test/mockito/junit4-java8/src/test/java/samples/powermockito/junit4/bugs/github510/ClassUsesInterfaceTest.java
modules/module-test/mockito/junit4-java8/src/test/java/samples/powermockito/junit4/bugs/github510/FizzBuzzTest.java
modules/module-test/mockito/junit4/src/test/java/samples/powermockito/junit4/bugs/github510/package-info.java
modules/module-test/mockito/pom.xml
modules/module-test/pom.xml
modules/pom.xml
pom.xml

Fix 
- #510 Static method mocking with Mockito 1.9.5 and Powermock fails with Java 8 Consumer Interface
- Issue with mocking static method in interfaces.

Fix #510 and other issue with interface with java8

---

core/src/main/java/org/powermock/core/transformers/impl/AbstractMainMockTransformer.java
core/src/main/java/org/powermock/core/transformers/impl/ClassMockTransformer.java
core/src/test/java/org/powermock/core/transformers/impl/ClassMockTransformerTest.java
core/src/test/java/powermock/test/support/ClassWithLargeMethods.java
modules/module-test/easymock/junit4-agent/src/test/java/samples/powermockito/junit4/agent/LargeMethodTest.java
modules/module-test/easymock/junit4-test/src/test/java/samples/junit4/largemethod/LargeMethodTest.java
modules/module-test/mockito/junit4-agent/src/test/java/samples/powermockito/junit4/agent/LargeMethodTest.java
modules/module-test/mockito/junit4/src/test/java/samples/powermockito/junit4/largemethod/LargeMethodTest.java
tests/utils/src/main/java/samples/largemethod/MethodExceedingJvmLimit.java

Negative consequence of code instrumentation is significant increase in code size. It can be especially problematic for large methods. When JVM limit is exceeded class loader is not able to load problematic class. This is manifested to user with enigmatic exception like:
Exception in thread "main" java.lang.ClassFormatError: Invalid method Code length 91299 in class file com/test/SomeClass
The solution to that problem is to override excessive method to throw more descriptive exception and allow users to mock/suppress such method.
More details on JVM method size limit: http://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.3

Ensuring JVM method size limit is never exceeded

---

.gitignore
changelog.txt
reflect/src/main/java/org/powermock/reflect/internal/WhiteboxImpl.java
reflect/src/test/java/org/powermock/reflect/WhiteBoxTest.java
reflect/src/test/java/org/powermock/reflect/testclasses/ClassWithInternalState.java

Here is the [issue I reported](https://github.com/jayway/powermock/issues/673)
Whitebox.setInternalState works with [private static final object](https://github.com/andreicristianpetcu/powermock/blob/6a2ce1d15221f87e192c8402b76d93f2b74e6d47/reflect/src/test/java/org/powermock/reflect/WhiteBoxTest.java#L293-L303)
```java
Whitebox.setInternalState(ClassWithInternalState.class, 
"staticFinalIntegerState", newValue);
```
Whitebox.setInternalState throws exception with private static final [primitive](https://github.com/andreicristianpetcu/powermock/blob/6a2ce1d15221f87e192c8402b76d93f2b74e6d47/reflect/src/test/java/org/powermock/reflect/WhiteBoxTest.java#L277-L283) or [String](https://github.com/andreicristianpetcu/powermock/blob/6a2ce1d15221f87e192c8402b76d93f2b74e6d47/reflect/src/test/java/o …

Fix #673: Add support for setting private static final fields

---

core/src/main/java/org/powermock/core/MockGateway.java
modules/module-test/mockito/junit4/src/test/java/samples/powermockito/junit4/getannotation/GetAnnotationTest.java
tests/utils/src/main/java/samples/annotationbased/AnnotatedClassDemo.java
tests/utils/src/main/java/samples/annotationbased/testannotations/RuntimeAnnotation.java

This is a fix for #676 
Powermock will no longer mock the class methods 
`isAnnotationPresent(Class)` and `getAnnotation(Class)`
and instead return the actual values.

Fix #676: Do not mock class annotations

---

modules/module-test/mockito/junit4/src/test/java/samples/powermockito/junit4/bugs/github668/GitHub668Test.java
modules/module-test/mockito/junit4/src/test/java/samples/powermockito/junit4/bugs/github668/package-info.java

powermock searches only for "java."  when checking if type is java system class
Create test - all work fine.

powermock-688 powermock searches only for "java." 

---

core/src/main/java/org/powermock/core/classloader/MockClassLoader.java
modules/module-test/mockito/junit4/pom.xml
modules/module-test/mockito/junit4/src/test/java/samples/powermockito/junit4/bugs/github704/PrepareForTestSignedTest.java
modules/module-test/mockito/junit4/src/test/java/samples/powermockito/junit4/bugs/github704/SomeClassUseSignedClasses.java
modules/module-test/mockito/junit4/src/test/java/samples/powermockito/junit4/bugs/github704/package-info.java

Fix #704 Pass protection domain for mocked classes

#704 PowerMockito 1.6.5 throws java.lang.SecurityException signer information mismatch

---

core/src/main/java/org/powermock/core/MockGateway.java
reflect/src/main/java/org/powermock/reflect/internal/WhiteboxImpl.java

When I started to use Powermock instead of Easymock, some test which used to take seconds started to take more than one minute. The proposed changes make performance of Powermock more or less comparable with Easymock.

Optimizations in powermock-reflect

---

powermock-core/src/main/java/org/powermock/core/MockGateway.java
tests/mockito/junit4-delegate/src/test/java/powermock/modules/test/mockito/junit4/delegate/parameterized/WhenNewTest.java
tests/mockito/junit4-rule-xstream/src/test/java/samples/powermockito/junit4/rule/xstream/WhenNewTest.java
tests/mockito/junit4/src/test/java/samples/powermockito/junit4/whennew/WhenNewCases.java
tests/utils/src/main/java/samples/classwithinnermembers/ClassWithInnerMembers.java

resolves issue #763 
- Added test cases to verify what used to be failing scenarios.
- Updated code to fix edge cases.
- Updated whitespace for consistency.
- Ported a testcase over from PowerMock to PowerMockito. Some of these fail in the xstream package and since they are existing issues, ignoring those tests in this case.

Issue #763: Fixing bug matching constructor with whenNew when first or last param is null.

---

powermock-core/src/main/java/org/powermock/tests/utils/impl/PowerMockIgnorePackagesExtractorImpl.java
powermock-core/src/test/java/org/powermock/tests/utils/impl/PowerMockIgnorePackagesExtractorImplTest.java

Fixes #772
Do a DFS on superclass + interfaces hierarchy to find all PowerMockIgnore annotations. Avoid duplication introduced by diamond interface hierarchies by storing packages in a set.

Fixes #772: PowerMockIgnorePackagesExtractorImpl should visit interfaces 

---

powermock-core/src/main/java/org/powermock/configuration/Configuration.java
powermock-core/src/main/java/org/powermock/configuration/ConfigurationType.java
powermock-core/src/main/java/org/powermock/configuration/GlobalConfiguration.java
powermock-core/src/main/java/org/powermock/configuration/MockitoConfiguration.java
powermock-core/src/main/java/org/powermock/configuration/PowerMockConfiguration.java
powermock-core/src/main/java/org/powermock/configuration/support/ConfigurationFactoryImpl.java
powermock-core/src/main/java/org/powermock/configuration/support/ConfigurationReaderBuilder.java
powermock-core/src/main/java/org/powermock/core/classloader/DeferSupportingClassLoader.java
powermock-core/src/main/java/org/powermock/tests/utils/impl/MockClassLoaderFactory.java
powermock-core/src/main/java/org/powermock/tests/utils/impl/PowerMockIgnorePackagesExtractorImpl.java
powermock-core/src/main/java/org/powermock/utils/ArrayUtil.java
powermock-core/src/main/java/org/powermock/utils/StringJoiner.java
powermock-core/src/test/java/org/powermock/configuration/ConfigurationFactoryImplTest.java
powermock-core/src/test/java/org/powermock/configuration/ConfigurationReaderTest.java
powermock-core/src/test/java/org/powermock/tests/utils/impl/PowerMockIgnorePackagesExtractorImplTest.java
powermock-core/src/test/resources/org/powermock/configuration.template
powermock-core/src/test/resources/org/powermock/configuration/test.properties
tests/mockito/junit4/src/main/java/samples/powermockito/junit4/bugs/github801/GlobalPowerMockIgnore.java
tests/mockito/junit4/src/test/java/samples/powermockito/junit4/bugs/github801/GlobalPowerMockIgnoreTest.java
tests/mockito/junit4/src/test/resources/org/powermock/configuration.properties

Fix #801 Add ability to set global ignore with using `configuration.properties` file.

Implement #801 PowerMock Configuration: Global Ignore

---

build.gradle
config/checkstyle/checkstyle.xml

[CONTRIBUTING.md](https://github.com/powermock/powermock/blob/master/CONTRIBUTING.md) mentions these coding conventions:
> We use (4) spaces instead of tabs. Make sure line ending is Unix style (LF).
I have converted these conventions into a Checkstyle configuration:
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
<module name="FileTabCharacter"/>
<module name="RegexpMultiline">
<property name="format" value="(?s:(\r|\r\n).*)"/>
<property name="message" value="Use Unix style (LF) line endings instead of Mac style (CR) or Windows style (CRLF)"/>
</module>
<module name="TreeWalker">
<module name="Indentation"/>
</module>
</module>
```
However, running …

Add Checkstyle to Powermock Build Process
